"""South India state, district, and city data for location dropdowns."""

BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
URGENCY_LEVELS = ["Normal", "High", "Critical"]

LOCATION_TREE = {
    "Andhra Pradesh": {
        "Alluri Sitharama Raju": ["Paderu", "Araku Valley", "Rampachodavaram"],
        "Anakapalli": ["Anakapalli", "Narsipatnam"],
        "Anantapur": ["Anantapur", "Guntakal", "Tadipatri"],
        "Annamayya": ["Rayachoti", "Rajampet", "Madanapalle"],
        "Bapatla": ["Bapatla", "Chirala", "Repalle"],
        "Chittoor": ["Chittoor", "Punganur", "Nagari"],
        "East Godavari": ["Rajahmundry", "Kovvur"],
        "Eluru": ["Eluru", "Nuzvid"],
        "Guntur": ["Guntur", "Tenali", "Mangalagiri"],
        "Kakinada": ["Kakinada", "Peddapuram"],
        "Konaseema": ["Amalapuram", "Razole", "Mandapeta"],
        "Krishna": ["Machilipatnam", "Gudivada"],
        "Kurnool": ["Kurnool", "Adoni", "Yemmiganur"],
        "Nandyal": ["Nandyal", "Dhone", "Atmakur"],
        "NTR": ["Vijayawada", "Nandigama", "Jaggayyapeta"],
        "Palnadu": ["Narasaraopet", "Sattenapalle", "Piduguralla"],
        "Parvathipuram Manyam": ["Parvathipuram", "Salur"],
        "Prakasam": ["Ongole", "Markapur", "Kandukur"],
        "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur"],
        "Sri Sathya Sai": ["Puttaparthi", "Hindupur", "Dharmavaram"],
        "Srikakulam": ["Srikakulam", "Palasa", "Tekkali"],
        "Tirupati": ["Tirupati", "Srikalahasti", "Sullurupeta"],
        "Visakhapatnam": ["Visakhapatnam", "Bheemunipatnam"],
        "Vizianagaram": ["Vizianagaram", "Bobbili"],
        "West Godavari": ["Bhimavaram", "Tadepalligudem", "Narasapuram"],
        "YSR": ["Kadapa", "Proddatur", "Pulivendula"],
    },
    "Karnataka": {
        "Bagalkot": ["Bagalkot", "Jamkhandi", "Badami"],
        "Ballari": ["Ballari", "Kampli"],
        "Belagavi": ["Belagavi", "Gokak", "Athani"],
        "Bengaluru Rural": ["Devanahalli", "Doddaballapur", "Nelamangala"],
        "Bengaluru Urban": ["Bangalore", "Yelahanka", "Kengeri"],
        "Bidar": ["Bidar", "Basavakalyan"],
        "Chamarajanagar": ["Chamarajanagar", "Kollegal"],
        "Chikkaballapur": ["Chikkaballapur", "Chintamani"],
        "Chikkamagaluru": ["Chikkamagaluru", "Kadur"],
        "Chitradurga": ["Chitradurga", "Hiriyur"],
        "Dakshina Kannada": ["Mangalore", "Puttur", "Bantwal"],
        "Davanagere": ["Davanagere", "Harihar"],
        "Dharwad": ["Dharwad", "Hubli", "Navalgund"],
        "Gadag": ["Gadag", "Mundargi"],
        "Hassan": ["Hassan", "Arsikere"],
        "Haveri": ["Haveri", "Ranebennur"],
        "Kalaburagi": ["Kalaburagi", "Afzalpur"],
        "Kodagu": ["Madikeri", "Virajpet", "Somwarpet"],
        "Kolar": ["Kolar", "Malur"],
        "Koppal": ["Koppal", "Gangavathi"],
        "Mandya": ["Mandya", "Srirangapatna"],
        "Mysuru": ["Mysore", "Nanjangud", "Hunsur"],
        "Raichur": ["Raichur", "Sindhanur"],
        "Ramanagara": ["Ramanagara", "Channapatna"],
        "Shivamogga": ["Shivamogga", "Sagar", "Bhadravati"],
        "Tumakuru": ["Tumakuru", "Tiptur"],
        "Udupi": ["Udupi", "Kundapura", "Karkala"],
        "Uttara Kannada": ["Karwar", "Sirsi", "Dandeli"],
        "Vijayanagara": ["Hosapete", "Hagaribommanahalli"],
        "Vijayapura": ["Vijayapura", "Indi"],
        "Yadgir": ["Yadgir", "Shahpur"],
    },
    "Kerala": {
        "Alappuzha": ["Alappuzha", "Cherthala", "Kayamkulam"],
        "Ernakulam": ["Kochi", "Ernakulam", "Aluva", "Muvattupuzha"],
        "Idukki": ["Painavu", "Thodupuzha", "Munnar"],
        "Kannur": ["Kannur", "Thalassery", "Payyanur"],
        "Kasaragod": ["Kasaragod", "Kanhangad"],
        "Kollam": ["Kollam", "Punalur", "Karunagappally"],
        "Kottayam": ["Kottayam", "Changanassery", "Pala"],
        "Kozhikode": ["Kozhikode", "Vadakara", "Koyilandy"],
        "Malappuram": ["Malappuram", "Manjeri", "Tirur"],
        "Palakkad": ["Palakkad", "Ottapalam", "Chittur"],
        "Pathanamthitta": ["Pathanamthitta", "Adoor", "Thiruvalla"],
        "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
        "Thrissur": ["Thrissur", "Irinjalakuda", "Guruvayur"],
        "Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery"],
    },
    "Lakshadweep": {
        "Lakshadweep": ["Kavaratti", "Agatti", "Amini", "Andrott", "Minicoy"],
    },
    "Puducherry": {
        "Karaikal": ["Karaikal", "Nedungadu", "Tirunallar"],
        "Mahe": ["Mahe", "Palloor"],
        "Puducherry": ["Puducherry", "Oulgaret", "Villianur", "Bahour"],
        "Yanam": ["Yanam"],
    },
    "Tamil Nadu": {
        "Ariyalur": ["Ariyalur", "Jayankondam"],
        "Chengalpattu": ["Chengalpattu", "Tambaram", "Mahabalipuram"],
        "Chennai": ["Chennai", "Tondiarpet", "Mylapore"],
        "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam"],
        "Cuddalore": ["Cuddalore", "Chidambaram", "Neyveli"],
        "Dharmapuri": ["Dharmapuri", "Harur"],
        "Dindigul": ["Dindigul", "Palani", "Kodaikanal"],
        "Erode": ["Erode", "Gobichettipalayam", "Bhavani"],
        "Kallakurichi": ["Kallakurichi", "Ulundurpet"],
        "Kancheepuram": ["Kancheepuram", "Sriperumbudur"],
        "Kanniyakumari": ["Nagercoil", "Kanniyakumari", "Marthandam"],
        "Karur": ["Karur", "Kulithalai"],
        "Krishnagiri": ["Krishnagiri", "Hosur"],
        "Madurai": ["Madurai", "Melur", "Thirumangalam"],
        "Mayiladuthurai": ["Mayiladuthurai", "Sirkazhi"],
        "Nagapattinam": ["Nagapattinam", "Vedaranyam"],
        "Namakkal": ["Namakkal", "Tiruchengode"],
        "Nilgiris": ["Udhagamandalam", "Coonoor", "Gudalur"],
        "Perambalur": ["Perambalur"],
        "Pudukkottai": ["Pudukkottai", "Aranthangi"],
        "Ramanathapuram": ["Ramanathapuram", "Paramakudi", "Rameswaram"],
        "Ranipet": ["Ranipet", "Arcot"],
        "Salem": ["Salem", "Mettur", "Attur"],
        "Sivaganga": ["Sivaganga", "Karaikudi"],
        "Tenkasi": ["Tenkasi", "Sankarankovil"],
        "Thanjavur": ["Thanjavur", "Kumbakonam", "Pattukkottai"],
        "Theni": ["Theni", "Bodinayakanur", "Periyakulam"],
        "Thoothukudi": ["Thoothukudi", "Kovilpatti", "Tiruchendur"],
        "Tiruchirappalli": ["Tiruchirappalli", "Srirangam", "Manapparai"],
        "Tirunelveli": ["Tirunelveli", "Ambasamudram"],
        "Tirupathur": ["Tirupathur", "Vaniyambadi", "Ambur"],
        "Tiruppur": ["Tiruppur", "Dharapuram", "Udumalaipettai"],
        "Tiruvallur": ["Tiruvallur", "Avadi", "Ponneri"],
        "Tiruvannamalai": ["Tiruvannamalai", "Arani"],
        "Tiruvarur": ["Tiruvarur", "Mannargudi"],
        "Vellore": ["Vellore", "Gudiyatham"],
        "Viluppuram": ["Viluppuram", "Tindivanam"],
        "Virudhunagar": ["Virudhunagar", "Sivakasi", "Rajapalayam"],
    },
    "Telangana": {
        "Adilabad": ["Adilabad", "Utnoor"],
        "Bhadradri Kothagudem": ["Kothagudem", "Bhadrachalam"],
        "Hanumakonda": ["Hanumakonda", "Kazipet"],
        "Hyderabad": ["Hyderabad", "Secunderabad"],
        "Jagtial": ["Jagtial", "Korutla"],
        "Jangaon": ["Jangaon"],
        "Jayashankar Bhupalpally": ["Bhupalpally"],
        "Jogulamba Gadwal": ["Gadwal", "Alampur"],
        "Kamareddy": ["Kamareddy", "Banswada"],
        "Karimnagar": ["Karimnagar", "Huzurabad"],
        "Khammam": ["Khammam", "Madhira"],
        "Kumuram Bheem Asifabad": ["Asifabad", "Kagaznagar"],
        "Mahabubabad": ["Mahabubabad", "Dornakal"],
        "Mahabubnagar": ["Mahabubnagar", "Jadcherla"],
        "Mancherial": ["Mancherial", "Bellampalli"],
        "Medak": ["Medak", "Narsapur"],
        "Medchal-Malkajgiri": ["Malkajgiri", "Medchal", "Kukatpally"],
        "Mulugu": ["Mulugu"],
        "Nagarkurnool": ["Nagarkurnool", "Achampet"],
        "Nalgonda": ["Nalgonda", "Miryalaguda"],
        "Narayanpet": ["Narayanpet"],
        "Nirmal": ["Nirmal", "Bhainsa"],
        "Nizamabad": ["Nizamabad", "Bodhan"],
        "Peddapalli": ["Peddapalli", "Ramagundam"],
        "Rajanna Sircilla": ["Sircilla", "Vemulawada"],
        "Rangareddy": ["Shamshabad", "Ibrahimpatnam", "Chevella"],
        "Sangareddy": ["Sangareddy", "Zaheerabad"],
        "Siddipet": ["Siddipet", "Gajwel"],
        "Suryapet": ["Suryapet", "Kodad"],
        "Vikarabad": ["Vikarabad", "Tandur"],
        "Wanaparthy": ["Wanaparthy"],
        "Warangal": ["Warangal", "Narsampet"],
        "Yadadri Bhuvanagiri": ["Bhuvanagiri", "Yadagirigutta"],
    },
}
